### ISSUE TITLE
Incorrect comment in header file re default address.  No useful documentation...

### ISSUE THREAD

**Issue by gitcnd** [adafruit/Adafruit_MPU6050#22] opened 2022-07-13 16:30 UTC
This is written in the header file, and is **WRONG**:-

`#define MPU6050_I2CADDR_DEFAULT   0x68  ///< MPU6050 default i2c address w/ AD0 high
`

The I2C address is 0x68 when AD0 is **LOW**
The I2C address is 0x69 when AD0 is HIGH.

This is important, because many people have to change the address to 0x69 (wire AD0 to VCC) in order for the MPU6050 to co-exist with most RTC clock modules, which also use 0x68 I2c (and cannot be changed).

It appears that we can pass the I2C address into the begin() function?  This needs to be documented.

You've got a README.md (yay!) except it doesn't tell you anything about how to use the lib (boo!!):  Please include basic library usage functions into the README, so we know how to use this from page 1....

**Comment by caternuson** [comment] 2022-09-21 16:45
Closing. Dupe of #25

**Closed by caternuson** 2022-09-21 16:45 UTC
